### ISSUE TITLE
when used debugging mode "sh -x obfuscated script" then the original script is seen

### ISSUE THREAD

**Issue by sushmithakumar** [willshiao/node-bash-obfuscate#17]

**Comment by willshiao** [comment]
See https://github.com/willshiao/node-bash-obfuscate#whats-the-point-i-can-deobfuscate-it-so-easily. AFAIK, there isn't a way to do this that is robust to something like `sh -x` or simply replacing eval with echo. Base64 encoding will just add an extra step but still has the same flaws.
