### ISSUE TITLE
slightly better obfs

### ISSUE THREAD

**Issue by untoreh** [willshiao/node-bash-obfuscate#2]
not sure how much better this is but if you change the ouput from eval to heredoc it doesn't spit out the whole script during tracing at least on first approach, like this:
```
set +x ### I am annoyng
z="varsblabla"
exec bash <<< "$varsblabla"
```

**Comment by willshiao** [comment]
Yeah, it seems like the here string makes it more resilient to someone adding `set -x` to the top of the file, which would defeat the current strategy.

I updated the package to use the techinque you suggested.

**Comment by untoreh** [comment]
still about heredoc, you can define variables like [this](https://stackoverflow.com/a/8088167/2229761)

**Comment by untoreh** [comment]
@willshiao 
Apparently some quotes get lost with that syntax, this one should preserve quotes:
```bash
exec bash <<< "$(printf '%s' "$varsblabla")"
```
