### ISSUE TITLE
It's easy to deobfuscate

### ISSUE THREAD

**Issue by KhanhNguyen9872** [willshiao/node-bash-obfuscate#31]
## Replace eval to echo, now it's work
![image](https://user-images.githubusercontent.com/88880309/205567150-e22e730a-5180-4899-a1a6-a27f11ace5e7.png)

**Comment by willshiao** [comment]
Yes, I point this out in https://github.com/willshiao/node-bash-obfuscate#how-do-i-deobfuscate-a-script. This is a fundamental issue with bash scripts, but I am open to suggestions if you can think of a better way.
